# docker-compose.yml
version: '3.12'

services:
  web:
    build: .
    ports:
      - "5004:5004"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - DATABASE_CONNECTION=${DATABASE_CONNECTION}

    volumes:
      - .:/code

volumes:
  dbdata: